### ISSUE TITLE
这个是硬解，还是软解

### ISSUE THREAD

**Issue by jiaxin11** [zxrmmxt/SampleIjkplayerRtspPlay#2]
如何配置开启硬解码？

**Comment by zxrmmxt** [comment]
mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec", 1);

**Comment by ironmanpeng** [comment]
请教您一下，native源码您都做了哪些修改使得延迟有了很大的优化。我目前在做直播开发，望您指教，感谢！
